# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "eb982c18ff9757d9ff6c7b947f1bd927"
name = "prisma-app"
application_url = "https://parks-age-saving-arm.trycloudflare.com"
embedded = true

[webhooks]
api_version = "2026-04"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://parks-age-saving-arm.trycloudflare.com/api/auth/callback" ]

[build]
automatically_update_urls_on_dev = true
